#!/bin/sh
GNUMAKE=make
os=`uname -s`
if [ "${os}" = "Darwin" ];
then
  GNUMAKE=gnumake
fi
rm -f ../bin/picolisp ../bin/picolispx
$GNUMAKE clean
# $GNUMAKE debug=yes target=pil32 2>&1 | tee make.log
$GNUMAKE target=pil32 2>&1 | tee make.log
